#services:
 # fastapi-app-service:
  #  build: .
   # ports:
    #  - "0:8000"   # Container port 8000 mapped to a random free host port
    #environment:
     # - APP_MODE=multi-container
    #restart: unless-stopped



services:
  fastapi-app-service:
    build: .
    restart: unless-stopped
    environment:
      - APP_MODE=multi-container

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - fastapi-app-service
