kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001   # NodePort inside cluster
        hostPort: 30001        # Maps to localhost
        protocol: TCP
  - role: worker
